In [1]:
import torch
import numpy as np
import pickle
from collections import Counter

In [2]:
label = []

with open('Train/y_train.txt') as f:
    for line in f.readlines():
        label.append(line.strip())

print(len(label))
print(Counter(label))
print(sorted(set(label)))

7767
Counter({'5': 1423, '6': 1413, '4': 1293, '1': 1226, '2': 1073, '3': 987, '11': 90, '9': 75, '10': 60, '12': 57, '7': 47, '8': 23})
['1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9']


In [3]:
data = []

with open('Train/X_train.txt') as f:
    for line in f.readlines():
        data.append(line.strip())

print(len(data))

7767


In [7]:
arr = np.array(data)
print(arr.shape)
print(len(arr[0]))

(7767,)
10763


In [9]:
arr = np.loadtxt('Train/X_train.txt')
arr.shape

(7767, 561)

In [13]:
subject = np.loadtxt('Train/subject_id_train.txt')
labels = np.loadtxt('Train/y_train.txt')

np.unique(subject).tolist()

[1.0,
 3.0,
 5.0,
 6.0,
 7.0,
 8.0,
 11.0,
 14.0,
 15.0,
 16.0,
 17.0,
 19.0,
 21.0,
 22.0,
 23.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0]

In [30]:
train_agent_idx = np.argwhere(np.isin(subject, train_agent)).ravel()
test_agent_idx = np.argwhere(np.isin(subject, test_agent)).ravel()

test_agent_idx.shape

(729,)

In [34]:
train_y = np.loadtxt('Train/y_train.txt', dtype=np.int32)
print(np.unique(train_y))
print(Counter(train_y))
print()

test_y = np.loadtxt('Test/y_test.txt', dtype=np.int32)
print(np.unique(test_y))
print(Counter(test_y))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Counter({5: 1423, 6: 1413, 4: 1293, 1: 1226, 2: 1073, 3: 987, 11: 90, 9: 75, 10: 60, 12: 57, 7: 47, 8: 23})

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Counter({5: 556, 6: 545, 4: 508, 1: 496, 2: 471, 3: 420, 11: 49, 9: 32, 12: 27, 10: 25, 7: 23, 8: 10})


In [37]:
y_map = {v: k for k, v in enumerate(np.unique(train_y))}
new_train_y = np.vectorize(y_map.get)(train_y)
new_test_y = np.vectorize(y_map.get)(test_y)

print(Counter(new_train_y))
print(Counter(new_test_y))

Counter({4: 1423, 5: 1413, 3: 1293, 0: 1226, 1: 1073, 2: 987, 10: 90, 8: 75, 9: 60, 11: 57, 6: 47, 7: 23})
Counter({4: 556, 5: 545, 3: 508, 0: 496, 1: 471, 2: 420, 10: 49, 8: 32, 11: 27, 9: 25, 6: 23, 7: 10})


In [41]:
x_tensor = torch.tensor(arr).size()
y_tensor = new

torch.Size([7767, 561])

In [45]:
a = torch.rand(5, 8)
a.argmin(1)

tensor([5, 2, 4, 1, 0])

In [2]:
train_y = np.loadtxt(f"Train/y_train.txt", dtype=np.int32)

In [3]:
train_x = np.loadtxt(f"Train/X_train.txt")
train_x.shape

(7767, 561)

In [8]:
for i in range(30):
    print(np.max(train_x[i]), np.min(train_x[i]))

1.0 -1.0
0.9971274343247647 -1.0
0.9971274343247647 -1.0
1.0 -1.0
0.9974583817441267 -1.0
0.9974583817441267 -1.0
0.9965821026882202 -1.0
0.9965821026882202 -1.0
0.9967228316850825 -1.0
0.9944383747884191 -1.0
0.9948942903959743 -1.0
0.9975714841997638 -1.0
0.9990291881358793 -1.0
0.9985432195179826 -1.0
0.9716304680693764 -1.0
0.9950173831073981 -1.0
0.9991845889106441 -1.0
0.9989523596993228 -1.0
0.9211474178256389 -1.0
0.927424518643394 -1.0
0.9863220831448716 -1.0
0.9924206586892281 -1.0
0.9990320703593019 -1.0
0.9990320703593019 -1.0
0.9977236715343396 -1.0
0.9976213850380462 -1.0
0.989377841443942 -1.0
0.996891580533722 -1.0
0.9983023411066814 -1.0
0.9991108303863465 -1.0
